// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzOOi_nXrDOcrcJeTkoggBXd1PqFrP0bg',
    appId: '1:140223746923:web:9d2fb621421106e565b22e',
    messagingSenderId: '140223746923',
    projectId: 'hack-the-tank',
    authDomain: 'hack-the-tank.firebaseapp.com',
    storageBucket: 'hack-the-tank.appspot.com',
    measurementId: 'G-NRPRBM6J0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPbh9RQf_peg77rlUoOmCtO-3fzSy4hQ',
    appId: '1:140223746923:android:c270f29632d2c27c65b22e',
    messagingSenderId: '140223746923',
    projectId: 'hack-the-tank',
    storageBucket: 'hack-the-tank.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2d2wJLogsuiAgrrk51wN-_AuyTyWfiGI',
    appId: '1:140223746923:ios:c24d12889808bd0a65b22e',
    messagingSenderId: '140223746923',
    projectId: 'hack-the-tank',
    storageBucket: 'hack-the-tank.appspot.com',
    iosBundleId: 'com.example.hackTheTank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2d2wJLogsuiAgrrk51wN-_AuyTyWfiGI',
    appId: '1:140223746923:ios:931f83a9339f60f765b22e',
    messagingSenderId: '140223746923',
    projectId: 'hack-the-tank',
    storageBucket: 'hack-the-tank.appspot.com',
    iosBundleId: 'com.example.hackTheTank.RunnerTests',
  );
}
